// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Our Mission"
          title="Redefining Hyperbaric Care"
          description="We design and manufacture hard-shell hyperbaric chambers that blend medical-grade precision with intuitive design, ensuring safety, reliability, and unparalleled efficacy."
          imageSrc="http://img.b2bpic.net/free-photo/empty-laboratory-with-scientific-monitor-desk_482257-18203.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
