// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Support"
          title="Common Questions"
          description="Everything you need to know about our hyperbaric chambers and support."
          categories={[
            {
              name: "Safety",
              items: [
                {
                  question: "Are these chambers safe?",
                  answer: "Yes, our chambers are fully certified and undergo rigorous testing.",
                },
              ],
            },
            {
              name: "Maintenance",
              items: [
                {
                  question: "Is it hard to maintain?",
                  answer: "No, we've designed them for low-maintenance daily operation.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
