// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesComparison from '@/components/sections/features/FeaturesComparison';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesComparison
          tag="Why Choose Us"
          title="Safety & Excellence Built-in"
          description="Compare our standards to ordinary alternatives and see why medical and wellness professionals choose Oxyhelp."
          negativeItems={[
            "High maintenance overhead",
            "Proprietary, closed ecosystems",
            "Inconsistent safety certification",
          ]}
          positiveItems={[
            "Low-maintenance design",
            "Modular technology stack",
            "Full global medical validation",
            "User-centric safety protocols",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
