// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroTiltedCards
        tag="Defining the New Standard"
        title="Hyperbaric wellness technology"
        description="We offer modular, safe, and low-maintenance hyperbaric technology for those seeking supreme performance, recovery, and longevity."
        primaryButton={{
            text: "Book a Meeting",
            href: "#contact",
          }}
        secondaryButton={{
            text: "Learn More",
            href: "#about",
          }}
        items={[{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784997541498-w4h3yi5a.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784997541497-a58bhqcb.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784997541498-hwgxlste.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784997541500-9uhv5eia.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784997541498-w4h3yi5a.jpg"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
