// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesImageBento
          tag="Technology"
          title="Engineering Superiority"
          description="Explore the advanced components and high-standard engineering behind our hyperbaric chambers."
          items={[
            {
              title: "Precision Hardware",
              description: "High-grade atmospheric controls.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-smiley-nurses-work_23-2149341556.jpg",
            },
            {
              title: "Comfort Interior",
              description: "Spacious and intuitive cabin.",
              imageSrc: "http://img.b2bpic.net/free-photo/cat-scan-machine-hospital-with-no-people_637285-4945.jpg",
            },
            {
              title: "Real-time Metrics",
              description: "Advanced health data monitoring.",
              imageSrc: "http://img.b2bpic.net/free-photo/african-american-med-school-pupil-studies-pharmacology-notes-library_482257-117779.jpg",
            },
            {
              title: "Wellness Aesthetic",
              description: "Fits clinical and spa environments.",
              imageSrc: "http://img.b2bpic.net/free-photo/electromagnetic-therapy-back-physiotherapist-doctor-uses-medical-equipment-highly-effective-pain-treatment-inflammation-back-magnetic-field-rehabilitation-magnetotherapy_169016-41688.jpg",
            },
            {
              title: "Structural Integrity",
              description: "Certified modular frame.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-mechanics-holding-laptop-diagnostics-tool-truck-workshop_342744-1334.jpg",
            },
            {
              title: "Secure Access",
              description: "Reliable entry mechanisms.",
              imageSrc: "http://img.b2bpic.net/free-photo/red-themed-circuit-board-with-chip-close-up_23-2148284294.jpg",
            },
            {
              title: "Global Deployment",
              description: "Validated for worldwide use.",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-man-ready-get-ct-scan_23-2149341496.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
