// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesImageBento
          tag="Technology"
          title="Engineering Superiority"
          description="Explore the advanced components and high-standard engineering behind our hyperbaric chambers."
          items={[
            {
              title: "Precision Hardware",
              description: "High-grade atmospheric controls.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784999570483-cmt9t8lz.jpg",
            },
            {
              title: "Comfort Interior",
              description: "Spacious and intuitive cabin.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GdLzVph1aPQWDuyELHp7aLXPvp/uploaded-1784997541498-hwgxlste.jpg",
            },
            {
              title: "Real-time Metrics",
              description: "Advanced health data monitoring.",
              imageSrc: "http://img.b2bpic.net/free-photo/african-american-med-school-pupil-studies-pharmacology-notes-library_482257-117779.jpg",
            },
            {
              title: "Wellness Aesthetic",
              description: "Fits clinical and spa environments.",
              imageSrc: "https://images.pexels.com/photos/36450259/pexels-photo-36450259.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=36450259",
            },
            {
              title: "Structural Integrity",
              description: "Certified modular frame.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-mechanics-holding-laptop-diagnostics-tool-truck-workshop_342744-1334.jpg",
            },
            {
              title: "Secure Access",
              description: "Reliable entry mechanisms.",
              imageSrc: "http://img.b2bpic.net/free-photo/red-themed-circuit-board-with-chip-close-up_23-2148284294.jpg",
            },
            {
              title: "Global Deployment",
              description: "Validated for worldwide use.",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-man-ready-get-ct-scan_23-2149341496.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
