// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "science" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ScienceSection(): React.JSX.Element {
  return (
    <div id="science" data-section="science">
        <SectionErrorBoundary name="science">
              <MetricsSimpleCards
          tag="Impact"
          title="Proven Efficacy"
          description="Our technology is backed by data and trusted by global leaders in medicine and sports performance."
          metrics={[
            {
              value: "99.9%",
              description: "Operational uptime rate",
            },
            {
              value: "120+",
              description: "Certified global facilities",
            },
            {
              value: "25k+",
              description: "Successful treatment sessions",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
