// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialSection(): React.JSX.Element {
  return (
    <div id="social" data-section="social">
        <SectionErrorBoundary name="social">
              <SocialProofMarquee
          tag="Verified Global Presence"
          title="Trusted Globally"
          description="Featured in leading medical publications and used by international facilities."
          names={[
            "MedTech Today",
            "SportPerformance Weekly",
            "Clinical Innovations",
            "Global Health Forum",
            "Hyperbaric Journal",
            "Wellness Solutions",
            "Modern Medicine",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
