// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamStackedCards from '@/components/sections/team/TeamStackedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamStackedCards
          tag="Leadership"
          title="The Minds Behind Oxyhelp"
          description="Our team of engineers, medics, and innovators drives the future of hyperbaric technology."
          members={[
            {
              name: "Alex Rivet",
              role: "Lead Engineer",
              imageSrc: "http://img.b2bpic.net/free-photo/family-doctor-doctor-s-office_23-2148168431.jpg",
            },
            {
              name: "Sarah Chen",
              role: "Head of Medical Validation",
              imageSrc: "http://img.b2bpic.net/free-photo/businesswoman-working-warehouse_329181-12823.jpg",
            },
            {
              name: "Marcus Thorne",
              role: "Product Director",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-exhausted-workaholic-man-manager-typing-financial-strategy-using-laptop-computer-while-sitting-desk-table-business-company-office_482257-2321.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
