// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Trust"
          title="Validation from Professionals"
          description="Trusted by doctors, athletes, and wellness studios worldwide."
          testimonials={[
            {
              name: "Dr. Elena Rossi",
              role: "Clinician",
              quote: "The reliability of Oxyhelp chambers is unmatched in my clinical practice.",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-happy-bearded-man-suit-laughing-smiling-standing-white-background_1258-155212.jpg",
            },
            {
              name: "James L.",
              role: "Pro Athlete",
              quote: "My recovery time has significantly decreased since using Oxyhelp technology.",
              imageSrc: "http://img.b2bpic.net/free-photo/horizontal-portrait-beautiful-positive-young-european-female-blue-shirt-dress-relaxing-home-looking-front-with-easy-carefree-smile_343059-3894.jpg",
            },
            {
              name: "Maria K.",
              role: "Clinic Owner",
              quote: "A perfect blend of user-friendly technology and clinical safety.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-portrait-young-handsome-successful-man_1163-5475.jpg",
            },
            {
              name: "Robert D.",
              role: "Physiotherapist",
              quote: "Highly recommended for any facility focused on patient longevity.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-african-american-girl-sitting-cafe_1262-3083.jpg",
            },
            {
              name: "Sarah W.",
              role: "Wellness Director",
              quote: "Our clients love the intuitive design and the immediate safety assurance.",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-young-businesswoman-smiling-camera_74855-3966.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
